### PR TITLE
Add content for Namadillo MASP and Transfer sections

### PR DESCRIPTION
**Pull request by iskay**
- add steps and screencaps to the MASP, IBC and Transfers pages of the Namadillo section

### CODE REVIEW

**Comment by brentstone** [comment]
legend, thx @iskay! Assume this is still WIP?

**Comment by iskay** [comment]
I was going to say merge now and add the IBC section later... but actually I think I can finish it up IBC also in the next day or so

**Comment by iskay** [comment]
@brentstone IBC section is finished, it's good to merge (pending review)

**Review by brentstone — APPROVED** [review]
Looks awesome from a first glance. Going to approve and merge now and then have someone on the Heliax interface team look over it and make a follow-up PR if needed.

**Pull request merged**
