### PR TITLE
Update PoS `objects-and-txs.md`

### PR DESCRIPTION
**Pull request by brentstone**
Update with the latest details on the proof-of-stake data structures and transactions.

### CODE REVIEW

**Comment by bengtlofgren** [comment]
Are these ready @brentstone

**Comment by bengtlofgren** [comment]
How about now?

**Comment by brentstone** [comment]
> How about now?

No

**Comment by bengtlofgren** [comment]
How about now?

**Comment by brentstone** [comment]
> How about now? Are we there yet?

Lol noooooo

**Pull request closed without merging**
